[package]
name = "bfv"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }

arithmetic = { path="../arithmetic" }
